version: '3'

services:
  # ${LARAVEL_APACHE_PHP_SERVER}:
  #   build:
  #       context: ./back/laravel
  yii2:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./back/yii2:/app:delegated
    ports:
      - '8080:80'
    links:
      - db
    # environment:
    #   PHP_ENABLE_XDEBUG: 1
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE : yii2
      MYSQL_USER: claudejanz
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
  vuejs:
    image: node:10
    ports:
      - '8083:8080'
    volumes:
      - ./front/vuejs:/home/node/app:delegated
    working_dir: /home/node/app
    command: "npm run serve"
