version: '3.1'

services:
  # laravel:
  #   build:
  #     dockerfile: Dockerfile
  #     context: 'docker/laravel'
  #     args:
  #       - PHP_BASE_IMAGE_VERSION=${PHP_BASE_IMAGE_VERSION}
  #   volumes:
  #     - ./back/laravel:/app/:delegated
  #     # - ./docker/laravel/my.conf:/etc/apache2/sites-enabled/my.conf
  #   ports:
  #     - '8081:80'
  #   links:
  #     - db
  #   # command: sed -i -e 's/\/var\/www\/html/kiki/g' /etc/apache2/sites-enabled/*.conf; 
      
  yii:
    image: yiisoftware/yii2-php:7.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./back/yii2:/app:delegated
    ports:
      - '8080:80'
    links:
      - db
    
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d

  vuejs:
    image: node:10
    ports:
      - '8083:8080'
    volumes:
      - ./front/vuejs:/home/node/app:delegated
    working_dir: /home/node/app
    command: "npm run serve"
