version: '3.3'

services:
  laravel:
    build:
      context: '.docker/laravel'
      args:
        - PHP_BASE_IMAGE_VERSION=${PHP_BASE_IMAGE_VERSION}
    volumes:
      - ./back/laravel:/app/
    ports:
      - '8081:80'
    links:
      - db
      
  yii:
    build:
      context: '.docker/yii'
      args:
        - PHP_BASE_IMAGE_VERSION=${PHP_BASE_IMAGE_VERSION}
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache
      - ./back/yii2:/app
    ports:
      - '8080:80'
    links:
      - db
    
    
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./.cache/mysql:/var/lib/mysql

  vuejs:
    build:
      dockerfile: Dockerfile
      context: '.docker/vuejs'
    ports:
      - '8083:8080'
    volumes:
      - ./front/vuejs:/home/app
    working_dir: /home/app
    

  symfony:
    build:
      context: '.docker/symfony'
      args:
        - PHP_BASE_IMAGE_VERSION=${PHP_BASE_IMAGE_VERSION}
    volumes:
      - ./back/symfony:/app/
    ports:
      - '8082:80'
    links:
      - db

